src/Entity/Panier.php
<?php
    /**
     * Created by PhpStorm.
     * User: thomas
     * Date: 2018-09-27
     * Time: 13:49
     */

    namespace App\Entity;


    class Panier
    {

        /**
         * @var []Produit
         */
        protected $produits = [];

        public function addProduct(Produit $produit) {
            $this->produits[] = $produit;
        }

        public function getVat() {
            $totalTVA = 0.0;
            foreach ($this->produits as $produit) {
                if ($produit->isBook()) {
                    $totalTVA += $produit->getPrix() * 0.055;
                } else {
                    $totalTVA += $produit->getPrix() * 0.2;
                }
            }
            return round($totalTVA, 2);
        }

        public function getTransportation() {
            if ($this->getHT() > 50.0) {
                return 0.0;
            } else {
                return 5.0;
            }
        }

        public function getHT() {
            $totalHT = 0.0;
            foreach ($this->produits as $produit) {
                $totalHT += $produit->getPrix();
            }
            return round($totalHT,2);
        }

        public function getTotal() {
            $total = 0.0;
            $total += $this->getHT();
            $total += $this->getTransportation();
            $total += $this->getVat();
            return $total;
        }

        /**
         * @return mixed
         */
        public function getProduits()
        {
            return $this->produits;
        }

    }

src/Entity/Produit.php
<?php
    /**
     * Created by PhpStorm.
     * User: thomas
     * Date: 2018-09-27
     * Time: 14:00
     */

    namespace App\Entity;


    class Produit
    {

        /**
         * @var float
         */
        protected $prix;

        /**
         * @var bool
         */
        protected $isBook;

        public function __construct(float $prix, bool $isBook)
        {
            $this->isBook = $isBook;
            $this->prix = $prix;
        }

        /**
         * @return bool
         */
        public function isBook(): bool
        {
            return $this->isBook;
        }

        /**
         * @return float
         */
        public function getPrix(): float
        {
            return $this->prix;
        }

    }

src/Controller/PanierController.php
<?php

namespace App\Controller;

use App\Entity\Panier;
use App\Entity\Produit;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\Routing\Annotation\Route;

class PanierController extends AbstractController
{
    /**
     * @Route("/panier", name="panier")
     */
    public function index()
    {
        $panier = new Panier();
        $panier->addProduct(new Produit(70.0, true));
        $panier->addProduct(new Produit(20.0, false));
        return $this->render('panier/index.html.twig', [
            'panier' => $panier,
        ]);
    }
}

templates/base.html.twig
<!DOCTYPE html>
<html>
    <head>
        <meta charset="UTF-8">
        <title>{% block title %}Welcome!{% endblock %}</title>
        {% block stylesheets %}{% endblock %}
    </head>
    <body>
        {% block body %}{% endblock %}
        {% block javascripts %}{% endblock %}
    </body>
</html>

templates/panier/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Panier : {% endblock %}

{% block body %}
<style>
    .example-wrapper { margin: 1em auto; max-width: 800px; width: 95%; font: 18px/1.5 sans-serif; }
    .example-wrapper code { background: #F5F5F5; padding: 2px 6px; }
</style>

<div class="example-wrapper">
    {% for produit in panier.produits %}
        <p>{{ produit.prix }} {{ produit.isBook ? "Livre" : "Non Livre"}}</p>
    {% endfor %}
        <p id="tvaPrice">TVA : {{ panier.vat }}</p>
        <p id="transportPrice">Frais de port : {{ panier.transportation }}</p>
        <p id="totalPrice">Total : {{ panier.total }}</p>
</div>
{% endblock %}